### ISSUE TITLE
Design contribution proposal

### ISSUE THREAD

**Issue by ihtiht** [aerosol/Tabula#19]
Hi,

I am a graphic designer. I contribute to open source projects. I can contribute to this project if you need it. I can design a logo.  If you have a design idea, please do not hesitate to say it. 

I look forward to your feedback ..

**Comment by aerosol** [comment]
@ihtiht very cool, thank you! Would be nice to add some eye candy to the README, PR appreciated :+1:

**Comment by ihtiht** [comment]
Here are my designs;

![tabula](https://user-images.githubusercontent.com/36369736/40631007-c81c7f64-62e0-11e8-83dc-026ff8c3de3e.jpg)

If there is one you like, I can send it.

**Comment by aerosol** [comment]
Hey

IMHO the images resemble bulletpoints on a map (the pin drop symbol is universally associated with map markers I guess?). That makes it difficult to associate it with tables.

If you like any of the above, feel free to submit a PR and I'll happily merge.
If you'd like to give it a 2nd go, I'm open as well.

Thank you!
