### ISSUE TITLE
:only option only available in print_table

### ISSUE THREAD

**Issue by zoldar** [aerosol/Tabula#2]
`:only` option currently seems to be only (sic!) used in `print_table` and not in `render_table`.

**Comment by aerosol** [comment]
:+1:

**Comment by aerosol** [comment]
Giving this a closer look, I think it's fine - `render_table` has a different function signature and accepts `rows` which is in fact computed from `:only` by `print_table`. 
I fail to see anything wrong about it. Agree? Y/n?

**Comment by zoldar** [comment]
Agreed.
